const playlist = [
    { artist: 'Maestro Chives, Egzod, Neoni', song: 'Royalty [NCS Release]', url: 'music/Royalty [NCS Release].mp3' },
    { artist: 'Cartoon, Daniel Levi, Jéja', song: 'On & On (feat. Daniel Levi) [NCS RELEASE]', url: 'music/On & On (feat. Daniel Levi) [NCS Release].mp3' },
    { artist: 'Mqx, MVSTAFA', song: 'Want it All [NCS Release]', url: 'music/Want it All [NCS Release].mp3' },
    { artist: 'blackbear', song: 'hot girl bummer', url: 'music/blackbear hot girl bummer.mp3' },
    { artist: 'AVAION', song: 'Pieces', url: 'music/AVAION Pieces.mp3' },
    { artist: 'Baby Bash', song: 'Light Up (feat. Z-Ro, Berner & Baby-E)', url: 'music/Baby_Bash_Light_Up.mp3' },
    { artist: 'calum scott', song: 'rise', url: 'assets/music/calum scott rise.mp3' },
    { artist: 'Charli XCX', song: 'Break The Rules', url: 'assets/music/Charli XCX Break The Rules.mp3' },
    { artist: 'Charlie Heat & Ant Beale', song: 'Sunshine', url: 'assets/music/Charlie Heat & Ant Beale - Sunshine [Bass Boosted].mp3' },
    { artist: 'Flo Rida', song: 'Whistle baby', url: 'assets/music/Flo Rida Whistle baby.mp3' },
    { artist: 'Gaullin', song: 'Top Down', url: 'assets/music/Gaullin Top Down.mp3' },
    { artist: 'Freddie Gibbs', song: 'Still Livin', url: 'assets/music/gta_v_radio_los_santos_freddie_gibbs_still_livin.mp3' },
    { artist: 'Jay Rock Ft Kendrick Lamar', song: 'Hood Gone Love It', url: 'assets/music/Jay Rock Ft Kendrick Lamar Hood Gone Love It.mp3' },
    { artist: 'KELLIYON', song: 'SKY', url: 'assets/music/KELLIYON - SKY.mp3' },
    { artist: 'Unknown Artist', song: 'Last Time I Saw You', url: 'assets/music/Last Time I Saw You.mp3' },
    { artist: 'Lukas Graham', song: '7 Years', url: 'assets/music/Lukas Graham 7 Years.mp3' },
    { artist: 'Merkules', song: 'Old Town Road Remix', url: 'assets/music/Merkules - Old Town Road Remix(Lil Nas X &amp Billy Ray Cyrus).mp3' },
    { artist: 'Mike Perry', song: 'ONE LIFE', url: 'assets/music/Mike Perry ONE LIFE.mp3' },
    { artist: 'Mike Perry', song: 'One Life (Redhead & MarcComplexx Remix)', url: 'assets/music/Mike Perry One Life (Remix).mp3' },
    { artist: 'Mike Posner', song: 'I Took A Pill In Ibiza (Seeb Remix)', url: 'assets/music/Mike Posner Pill In Ibiza (Seeb Remix).mp3' },
    { artist: 'Miles & Miles', song: 'Shes So High', url: 'assets/music/Miles & Miles Shes So High.mp3' },
    { artist: 'Doja Cat', song: 'Paint The Town Red', url: 'assets/music/Doja.mp3' },
    { artist: 'The Script', song: 'Hall of Fame', url: 'assets/music/The-Script-Hall-of-Fame-Lyric-ft-william.mp3' },
    { artist: 'Imagine Dragons', song: 'Thunder Remix', url: 'assets/music/Thunder Remix - Imagine Dragons   Nhạc Hot Tik Tok.mp3' },
    { artist: 'Travis Scott, HVME', song: 'Goosebumps (Remix)', url: 'assets/music/Travis Scott, HVME - Goosebumps (Remix).mp3' },
    { artist: 'Sam Kramer', song: 'Vroom Vroom', url: 'assets/music/Vroom Vroom - Sam Kramer.mp3' },
    { artist: 'Wiz Khalifa', song: 'Roll Up', url: 'assets/music/Wiz Khalifa Roll Up.mp3' },
    { artist: 'Juice WRLD', song: 'Love Yourself', url: 'assets/music/☾Juice WRLD☽ ♛Love Yourself ♛.mp3' },
    { artist: 'YNW Melly', song: 'Mama Cry', url: 'music/Mama Cry.mp3' }
];
